// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'home_detail_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

HomeDetailList _$HomeDetailListFromJson(Map<String, dynamic> json) {
  return HomeDetailList(
      json['albumId'] as int,
      json['albumTitle'] as String,
      json['commentsCounts'] as int,
      json['coverSmall'] as String,
      json['createdAt'] as int,
      json['duration'] as int,
      json['favoritesCounts'] as int,
      json['id'] as int,
      json['isAuthorized'] as bool,
      json['isFree'] as bool,
      json['isPaid'] as bool,
      json['nickname'] as String,
      json['playPath32'] as String,
      json['playPath64'] as String,
      json['playPathAacv164'] as String,
      json['playPathAacv224'] as String,
      json['playsCounts'] as int,
      json['priceTypeId'] as int,
      json['sampleDuration'] as int,
      json['sharesCounts'] as int,
      json['tags'] as String,
      json['title'] as String,
      json['trackId'] as int,
      json['uid'] as int,
      json['updatedAt'] as int,
      json['userSource'] as int,
      json['contentUpdatedAt'] as int,
      json['enableShare'] as bool,
      json['isExternalUrl'] as bool,
      json['bubbleText'] as String,
      json['contentType'] as String,
      json['coverPath'] as String,
      json['displayClass'] as String,
      json['sharePic'] as String,
      json['subtitle'] as String,
      json['url'] as String,
      json['adId'] as int,
      json['adType'] as int,
      json['buttonShowed'] as bool,
      json['clickAction'] as int,
      json['clickType'] as int,
      json['cover'] as String,
      json['description'] as String,
      json['displayType'] as int,
      json['isAd'] as bool,
      json['isInternal'] as int,
      json['isLandScape'] as bool,
      json['isShareFlag'] as bool,
      json['link'] as String,
      json['name'] as String,
      json['openlinkType'] as int,
      json['realLink'] as String,
      json['targetId'] as int,
      json['categoryId'] as int,
      json['commentsCount'] as int,
      json['contractStatus'] as int,
      json['isFinished'] as int,
      json['lastUptrackAt'] as int,
      json['originalStatus'] as int,
      json['playsCount'] as int,
      json['priceTypeEnum'] as int,
      json['refundSupportType'] as int,
      json['tracksCount'] as int,
      json['vipFreeType'] as int,
      json['isDraft'] as bool,
      json['isFollowing'] as bool,
      json['isVipFree'] as bool,
      json['subscribeStatus'] as bool,
      json['infoType'] as String,
      json['materialType'] as String,
      json['pic'] as String,
      json['recSrc'] as String,
      json['recTrack'] as String,
      (json['discountedPrice'] as num)?.toDouble(),
      (json['price'] as num)?.toDouble(),
      (json['commentScore'] as num)?.toDouble(),
      (json['vipPrice'] as num)?.toDouble(),
      json['displayDiscountedPrice'] as String,
      json['displayPrice'] as String,
      json['displayVipPrice'] as String,
      json['priceUnit'] as String,
      json['columnType'] as int,
      json['specialId'] as int,
      json['footnote'] as String,
      json['channelId'] as int,
      json['onLineNum'] as int,
      json['channelName'] as String,
      json['coverRound'] as String,
      json['liveStatus'] as int,
      json['liveType'] as int,
      json['openType'] as int,
      json['participationCount'] as int,
      json['planLessonCount'] as int,
      json['nickName'] as String,
      json['actualStartAt'] as int,
      json['chatId'] as int,
      json['endAt'] as int,
      json['playCount'] as int,
      json['roomId'] as int,
      json['startAt'] as int,
      json['status'] as int,
      json['categoryName'] as String,
      json['coverLarge'] as String,
      json['coverMiddle'] as String);
}

Map<String, dynamic> _$HomeDetailListToJson(HomeDetailList instance) =>
    <String, dynamic>{
      'id': instance.id,
      'title': instance.title,
      'albumId': instance.albumId,
      'albumTitle': instance.albumTitle,
      'commentsCounts': instance.commentsCounts,
      'coverSmall': instance.coverSmall,
      'createdAt': instance.createdAt,
      'duration': instance.duration,
      'favoritesCounts': instance.favoritesCounts,
      'isAuthorized': instance.isAuthorized,
      'isFree': instance.isFree,
      'isPaid': instance.isPaid,
      'nickname': instance.nickname,
      'playPath32': instance.playPath32,
      'playPath64': instance.playPath64,
      'playPathAacv164': instance.playPathAacv164,
      'playPathAacv224': instance.playPathAacv224,
      'playsCounts': instance.playsCounts,
      'priceTypeId': instance.priceTypeId,
      'sampleDuration': instance.sampleDuration,
      'sharesCounts': instance.sharesCounts,
      'tags': instance.tags,
      'trackId': instance.trackId,
      'uid': instance.uid,
      'updatedAt': instance.updatedAt,
      'userSource': instance.userSource,
      'adId': instance.adId,
      'adType': instance.adType,
      'buttonShowed': instance.buttonShowed,
      'clickAction': instance.clickAction,
      'clickType': instance.clickType,
      'cover': instance.cover,
      'description': instance.description,
      'displayType': instance.displayType,
      'isAd': instance.isAd,
      'isInternal': instance.isInternal,
      'isLandScape': instance.isLandScape,
      'isShareFlag': instance.isShareFlag,
      'link': instance.link,
      'name': instance.name,
      'openlinkType': instance.openlinkType,
      'realLink': instance.realLink,
      'targetId': instance.targetId,
      'contentUpdatedAt': instance.contentUpdatedAt,
      'enableShare': instance.enableShare,
      'isExternalUrl': instance.isExternalUrl,
      'bubbleText': instance.bubbleText,
      'contentType': instance.contentType,
      'coverPath': instance.coverPath,
      'displayClass': instance.displayClass,
      'sharePic': instance.sharePic,
      'subtitle': instance.subtitle,
      'url': instance.url,
      'categoryId': instance.categoryId,
      'commentsCount': instance.commentsCount,
      'contractStatus': instance.contractStatus,
      'isFinished': instance.isFinished,
      'lastUptrackAt': instance.lastUptrackAt,
      'originalStatus': instance.originalStatus,
      'playsCount': instance.playsCount,
      'priceTypeEnum': instance.priceTypeEnum,
      'refundSupportType': instance.refundSupportType,
      'tracksCount': instance.tracksCount,
      'vipFreeType': instance.vipFreeType,
      'isDraft': instance.isDraft,
      'isFollowing': instance.isFollowing,
      'isVipFree': instance.isVipFree,
      'subscribeStatus': instance.subscribeStatus,
      'infoType': instance.infoType,
      'materialType': instance.materialType,
      'pic': instance.pic,
      'recSrc': instance.recSrc,
      'recTrack': instance.recTrack,
      'discountedPrice': instance.discountedPrice,
      'price': instance.price,
      'commentScore': instance.commentScore,
      'vipPrice': instance.vipPrice,
      'displayDiscountedPrice': instance.displayDiscountedPrice,
      'displayPrice': instance.displayPrice,
      'displayVipPrice': instance.displayVipPrice,
      'priceUnit': instance.priceUnit,
      'columnType': instance.columnType,
      'specialId': instance.specialId,
      'footnote': instance.footnote,
      'channelId': instance.channelId,
      'onLineNum': instance.onLineNum,
      'channelName': instance.channelName,
      'coverRound': instance.coverRound,
      'liveStatus': instance.liveStatus,
      'liveType': instance.liveType,
      'openType': instance.openType,
      'participationCount': instance.participationCount,
      'planLessonCount': instance.planLessonCount,
      'nickName': instance.nickName,
      'actualStartAt': instance.actualStartAt,
      'chatId': instance.chatId,
      'endAt': instance.endAt,
      'playCount': instance.playCount,
      'roomId': instance.roomId,
      'startAt': instance.startAt,
      'status': instance.status,
      'categoryName': instance.categoryName,
      'coverLarge': instance.coverLarge,
      'coverMiddle': instance.coverMiddle
    };
