// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'album.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Album _$AlbumFromJson(Map<String, dynamic> json) {
  return Album(
      json['ageLevel'] as int,
      json['albumId'] as int,
      json['authorizedExpireTime'] as int,
      json['authorizedTypeId'] as int,
      json['categoryId'] as int,
      json['contractStatus'] as int,
      json['createdAt'] as int,
      json['freeToPaidStatus'] as int,
      json['freeToPaidTime'] as int,
      json['lastUptrackAt'] as int,
      json['lastUptrackId'] as int,
      json['offlineReason'] as int,
      json['offlineType'] as int,
      json['originalStatus'] as int,
      json['playTimes'] as int,
      json['playTrackId'] as int,
      json['refundSupportType'] as int,
      json['saleScope'] as int,
      json['serialState'] as int,
      json['serializeStatus'] as int,
      json['shareSupportType'] as int,
      json['shares'] as int,
      json['status'] as int,
      json['subscribeCount'] as int,
      json['tracks'] as int,
      json['type'] as int,
      json['uid'] as int,
      json['unReadAlbumCommentCount'] as int,
      json['updatedAt'] as int,
      json['vipFreeType'] as int,
      json['autoStart'] as bool,
      json['canInviteListen'] as bool,
      json['canShareAndStealListen'] as bool,
      json['hasNew'] as bool,
      json['hasRecs'] as bool,
      json['isAuthorized'] as bool,
      json['isDefault'] as bool,
      json['isDraft'] as bool,
      json['isFavorite'] as bool,
      json['isNoCopyright'] as bool,
      json['isPaid'] as bool,
      json['isPublic'] as bool,
      json['isRecordDesc'] as bool,
      json['isVerified'] as bool,
      json['isVipFree'] as bool,
      json['is_default'] as bool,
      json['avatarPath'] as String,
      json['categoryName'] as String,
      json['coverLarge'] as String,
      json['coverLargePop'] as String,
      json['coverMiddle'] as String,
      json['coverOrigin'] as String,
      json['coverSmall'] as String,
      json['coverWebLarge'] as String,
      json['customSubTitle'] as String,
      json['customTitle'] as String,
      json['detailCoverPath'] as String,
      json['intro'] as String,
      json['introRich'] as String,
      json['lastUptrackCoverPath'] as String,
      json['lastUptrackTitle'] as String,
      json['nickname'] as String,
      json['other_title'] as String,
      json['recommendReason'] as String,
      json['salePoint'] as String,
      json['salePointPopup'] as String,
      json['shortIntro'] as String,
      json['shortIntroRich'] as String,
      json['tags'] as String,
      json['title'] as String);
}

Map<String, dynamic> _$AlbumToJson(Album instance) => <String, dynamic>{
      'ageLevel': instance.ageLevel,
      'albumId': instance.albumId,
      'authorizedExpireTime': instance.authorizedExpireTime,
      'authorizedTypeId': instance.authorizedTypeId,
      'categoryId': instance.categoryId,
      'contractStatus': instance.contractStatus,
      'createdAt': instance.createdAt,
      'freeToPaidStatus': instance.freeToPaidStatus,
      'freeToPaidTime': instance.freeToPaidTime,
      'lastUptrackAt': instance.lastUptrackAt,
      'lastUptrackId': instance.lastUptrackId,
      'offlineReason': instance.offlineReason,
      'offlineType': instance.offlineType,
      'originalStatus': instance.originalStatus,
      'playTimes': instance.playTimes,
      'playTrackId': instance.playTrackId,
      'refundSupportType': instance.refundSupportType,
      'saleScope': instance.saleScope,
      'serialState': instance.serialState,
      'serializeStatus': instance.serializeStatus,
      'shareSupportType': instance.shareSupportType,
      'shares': instance.shares,
      'status': instance.status,
      'subscribeCount': instance.subscribeCount,
      'tracks': instance.tracks,
      'type': instance.type,
      'uid': instance.uid,
      'unReadAlbumCommentCount': instance.unReadAlbumCommentCount,
      'updatedAt': instance.updatedAt,
      'vipFreeType': instance.vipFreeType,
      'autoStart': instance.autoStart,
      'canInviteListen': instance.canInviteListen,
      'canShareAndStealListen': instance.canShareAndStealListen,
      'hasNew': instance.hasNew,
      'hasRecs': instance.hasRecs,
      'isAuthorized': instance.isAuthorized,
      'isDefault': instance.isDefault,
      'isDraft': instance.isDraft,
      'isFavorite': instance.isFavorite,
      'isNoCopyright': instance.isNoCopyright,
      'isPaid': instance.isPaid,
      'isPublic': instance.isPublic,
      'isRecordDesc': instance.isRecordDesc,
      'isVerified': instance.isVerified,
      'isVipFree': instance.isVipFree,
      'is_default': instance.is_default,
      'avatarPath': instance.avatarPath,
      'categoryName': instance.categoryName,
      'coverLarge': instance.coverLarge,
      'coverLargePop': instance.coverLargePop,
      'coverMiddle': instance.coverMiddle,
      'coverOrigin': instance.coverOrigin,
      'coverSmall': instance.coverSmall,
      'coverWebLarge': instance.coverWebLarge,
      'customSubTitle': instance.customSubTitle,
      'customTitle': instance.customTitle,
      'detailCoverPath': instance.detailCoverPath,
      'intro': instance.intro,
      'introRich': instance.introRich,
      'lastUptrackCoverPath': instance.lastUptrackCoverPath,
      'lastUptrackTitle': instance.lastUptrackTitle,
      'nickname': instance.nickname,
      'other_title': instance.other_title,
      'recommendReason': instance.recommendReason,
      'salePoint': instance.salePoint,
      'salePointPopup': instance.salePointPopup,
      'shortIntro': instance.shortIntro,
      'shortIntroRich': instance.shortIntroRich,
      'tags': instance.tags,
      'title': instance.title
    };
